language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev

matrix:
  allow_failures:
    - php: '7.0'
  fast_finish: true

# https://github.com/composer/composer/pull/5127 using vendor for phpspec until this goes in PROD
script:
    - vendor/phpspec/phpspec/bin/phpspec run
    - phpunit -c app/

cache:
    composer: true
    directories: vendor
