services:
    options_resolver:
        class: Symfony\Component\OptionsResolver\OptionsResolver

    emagia.character.factory:
        class: Emagia\Component\CharacterFactory
        arguments:
            - '@options_resolver'

    emagia.orderus:
        class: Emagia\Component\Character
        factory: ['@emagia.character.factory', 'build']
        arguments:
            - 'Orderus'
            - {health: {min: 70, max: 100}}

#    emagia.example:
#        class: Emagia\Bundle\EmagiaBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
